name: teacher
description: "선생님 앱"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  flutter_webrtc: ^0.12.0+hotfix.1
  whiteboard: ^0.0.2
  flutter_drawing_board: ^0.9.4
  web_socket_channel: ^2.1.0

  http: ^1.2.2

  cupertino_icons: ^1.0.8

  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
