# Generated by Django 5.1.2 on 2024-10-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
